apiVersion: 1
datasources:
  - name: ClickHouse
    uid: vantage-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: vantage
      username: vantage
    secureJsonData:
      password: vantage
