// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: vantage/v1/vantage.proto

package vantagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseFlag int32

const (
	ParseFlag_PARSE_FLAG_UNSPECIFIED            ParseFlag = 0
	ParseFlag_PARSE_FLAG_TS_COLLECTOR_FALLBACK  ParseFlag = 1 // QK_TS_ZERO: per-peer header ts was zero
	ParseFlag_PARSE_FLAG_ADDPATH_HEURISTIC      ParseFlag = 2 // add-path decided structurally, not by caps
	ParseFlag_PARSE_FLAG_ATTR_DISCARDED_7606    ParseFlag = 3
	ParseFlag_PARSE_FLAG_TREAT_AS_WITHDRAW_7606 ParseFlag = 4
	ParseFlag_PARSE_FLAG_VERSION_UNPARSED       ParseFlag = 5
	ParseFlag_PARSE_FLAG_UNKNOWN_FAMILY         ParseFlag = 6 // x{afi}-{safi} fallback in use
	ParseFlag_PARSE_FLAG_CAPS_MISSING           ParseFlag = 7 // RM before Peer-Up / no OPENs on record
	// Some NLRI in this event was carried as raw bytes rather than decoded --
	// an EVPN route type this build does not type, or an unknown family.
	// Distinct from PARSE_FLAG_UNKNOWN_FAMILY, which means the family itself
	// was unrecognized.
	ParseFlag_PARSE_FLAG_NLRI_UNTYPED ParseFlag = 8
	// BGP-LS carried an NLRI type this build does not decode (Node, Link and
	// IPv4 and IPv6 Prefix NLRI, types 1 to 4, all decode). The bytes are
	// preserved in raw_reach/raw_unreach.
	ParseFlag_PARSE_FLAG_LS_NLRI_UNDECODED ParseFlag = 9
	// BGP-LS carried a TLV type this build does not recognize -- either inside
	// the BGP-LS Attribute (path attribute 29) or inside a Node/Link NLRI's own
	// TLV list (including a node descriptor's nested sub-TLVs). Unlike
	// PARSE_FLAG_LS_NLRI_UNDECODED (a whole NLRI *type* not handled), the
	// NLRI/attribute here decoded successfully; only one of its TLVs did not.
	// The raw TLV bytes are preserved in unknown_tlvs.
	ParseFlag_PARSE_FLAG_LS_TLV_UNKNOWN ParseFlag = 10
)

// Enum value maps for ParseFlag.
var (
	ParseFlag_name = map[int32]string{
		0:  "PARSE_FLAG_UNSPECIFIED",
		1:  "PARSE_FLAG_TS_COLLECTOR_FALLBACK",
		2:  "PARSE_FLAG_ADDPATH_HEURISTIC",
		3:  "PARSE_FLAG_ATTR_DISCARDED_7606",
		4:  "PARSE_FLAG_TREAT_AS_WITHDRAW_7606",
		5:  "PARSE_FLAG_VERSION_UNPARSED",
		6:  "PARSE_FLAG_UNKNOWN_FAMILY",
		7:  "PARSE_FLAG_CAPS_MISSING",
		8:  "PARSE_FLAG_NLRI_UNTYPED",
		9:  "PARSE_FLAG_LS_NLRI_UNDECODED",
		10: "PARSE_FLAG_LS_TLV_UNKNOWN",
	}
	ParseFlag_value = map[string]int32{
		"PARSE_FLAG_UNSPECIFIED":            0,
		"PARSE_FLAG_TS_COLLECTOR_FALLBACK":  1,
		"PARSE_FLAG_ADDPATH_HEURISTIC":      2,
		"PARSE_FLAG_ATTR_DISCARDED_7606":    3,
		"PARSE_FLAG_TREAT_AS_WITHDRAW_7606": 4,
		"PARSE_FLAG_VERSION_UNPARSED":       5,
		"PARSE_FLAG_UNKNOWN_FAMILY":         6,
		"PARSE_FLAG_CAPS_MISSING":           7,
		"PARSE_FLAG_NLRI_UNTYPED":           8,
		"PARSE_FLAG_LS_NLRI_UNDECODED":      9,
		"PARSE_FLAG_LS_TLV_UNKNOWN":         10,
	}
)

func (x ParseFlag) Enum() *ParseFlag {
	p := new(ParseFlag)
	*p = x
	return p
}

func (x ParseFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_vantage_v1_vantage_proto_enumTypes[0].Descriptor()
}

func (ParseFlag) Type() protoreflect.EnumType {
	return &file_vantage_v1_vantage_proto_enumTypes[0]
}

func (x ParseFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseFlag.Descriptor instead.
func (ParseFlag) EnumDescriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{0}
}

type PeerType int32

const (
	PeerType_PEER_TYPE_GLOBAL  PeerType = 0
	PeerType_PEER_TYPE_RD      PeerType = 1
	PeerType_PEER_TYPE_LOCAL   PeerType = 2
	PeerType_PEER_TYPE_LOC_RIB PeerType = 3
)

// Enum value maps for PeerType.
var (
	PeerType_name = map[int32]string{
		0: "PEER_TYPE_GLOBAL",
		1: "PEER_TYPE_RD",
		2: "PEER_TYPE_LOCAL",
		3: "PEER_TYPE_LOC_RIB",
	}
	PeerType_value = map[string]int32{
		"PEER_TYPE_GLOBAL":  0,
		"PEER_TYPE_RD":      1,
		"PEER_TYPE_LOCAL":   2,
		"PEER_TYPE_LOC_RIB": 3,
	}
)

func (x PeerType) Enum() *PeerType {
	p := new(PeerType)
	*p = x
	return p
}

func (x PeerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerType) Descriptor() protoreflect.EnumDescriptor {
	return file_vantage_v1_vantage_proto_enumTypes[1].Descriptor()
}

func (PeerType) Type() protoreflect.EnumType {
	return &file_vantage_v1_vantage_proto_enumTypes[1]
}

func (x PeerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerType.Descriptor instead.
func (PeerType) EnumDescriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{1}
}

type PeerEvent_Kind int32

const (
	PeerEvent_KIND_UNSPECIFIED PeerEvent_Kind = 0
	PeerEvent_KIND_UP          PeerEvent_Kind = 1
	PeerEvent_KIND_DOWN        PeerEvent_Kind = 2
	// KIND_VIEW_LOST is the collector saying it stopped being able to see
	// this peer, and it is NOT a Peer Down. A Peer Down is the router
	// stating that a BGP session dropped, carried on the wire with a reason
	// code (RFC 7854 sec 4.9). This is emitted when the BMP transport itself
	// ends -- the router said nothing, and there is no reason code to
	// report, so down_reason is left zero rather than invented.
	//
	// It exists because the absence of it was a live defect: KIND_DOWN was
	// emitted only on a PeerDown message, so a collector whose TCP session
	// simply dropped left its peers recorded up under what remains
	// max(session_id) for that (collector, router) forever, and every
	// current-state query served that frozen view as though it were live.
	// Collapsing the two into KIND_DOWN would have fixed the staleness by
	// fabricating a router statement; this keeps "the collector lost its
	// view" and "the router reported a session down" as the separate facts
	// they are.
	PeerEvent_KIND_VIEW_LOST PeerEvent_Kind = 3
)

// Enum value maps for PeerEvent_Kind.
var (
	PeerEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_UP",
		2: "KIND_DOWN",
		3: "KIND_VIEW_LOST",
	}
	PeerEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_UP":          1,
		"KIND_DOWN":        2,
		"KIND_VIEW_LOST":   3,
	}
)

func (x PeerEvent_Kind) Enum() *PeerEvent_Kind {
	p := new(PeerEvent_Kind)
	*p = x
	return p
}

func (x PeerEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_vantage_v1_vantage_proto_enumTypes[2].Descriptor()
}

func (PeerEvent_Kind) Type() protoreflect.EnumType {
	return &file_vantage_v1_vantage_proto_enumTypes[2]
}

func (x PeerEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerEvent_Kind.Descriptor instead.
func (PeerEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{21, 0}
}

type RouterId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	SysName       string                 `protobuf:"bytes,2,opt,name=sys_name,json=sysName,proto3" json:"sys_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterId) Reset() {
	*x = RouterId{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterId) ProtoMessage() {}

func (x *RouterId) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterId.ProtoReflect.Descriptor instead.
func (*RouterId) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{0}
}

func (x *RouterId) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RouterId) GetSysName() string {
	if x != nil {
		return x.SysName
	}
	return ""
}

type RouterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`   // "cisco", "juniper", "arista", "" if unknown
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`           // "iosxr", "nxos", "junos", "eos", "ios"
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // normalized, e.g. "10.2.3"; raw kept in sys_descr
	SysDescr      string                 `protobuf:"bytes,4,opt,name=sys_descr,json=sysDescr,proto3" json:"sys_descr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouterInfo) Reset() {
	*x = RouterInfo{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterInfo) ProtoMessage() {}

func (x *RouterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterInfo.ProtoReflect.Descriptor instead.
func (*RouterInfo) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{1}
}

func (x *RouterInfo) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *RouterInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RouterInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RouterInfo) GetSysDescr() string {
	if x != nil {
		return x.SysDescr
	}
	return ""
}

type PeerId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          PeerType               `protobuf:"varint,1,opt,name=type,proto3,enum=vantage.v1.PeerType" json:"type,omitempty"`
	PostPolicy    bool                   `protobuf:"varint,2,opt,name=post_policy,json=postPolicy,proto3" json:"post_policy,omitempty"` // L flag
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Asn           uint32                 `protobuf:"varint,4,opt,name=asn,proto3" json:"asn,omitempty"`
	BgpId         string                 `protobuf:"bytes,5,opt,name=bgp_id,json=bgpId,proto3" json:"bgp_id,omitempty"`
	Distinguisher uint64                 `protobuf:"varint,6,opt,name=distinguisher,proto3" json:"distinguisher,omitempty"`
	// O flag (RFC 8671): these are routes the router *sent* to the peer,
	// not routes it received. Crossed with post_policy this names which of
	// the four RIB streams a message belongs to; the collector treats each
	// as a distinct peer, with its own subject and sequence counter.
	AdjRibOut     bool `protobuf:"varint,7,opt,name=adj_rib_out,json=adjRibOut,proto3" json:"adj_rib_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerId) Reset() {
	*x = PeerId{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerId) ProtoMessage() {}

func (x *PeerId) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerId.ProtoReflect.Descriptor instead.
func (*PeerId) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{2}
}

func (x *PeerId) GetType() PeerType {
	if x != nil {
		return x.Type
	}
	return PeerType_PEER_TYPE_GLOBAL
}

func (x *PeerId) GetPostPolicy() bool {
	if x != nil {
		return x.PostPolicy
	}
	return false
}

func (x *PeerId) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *PeerId) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *PeerId) GetBgpId() string {
	if x != nil {
		return x.BgpId
	}
	return ""
}

func (x *PeerId) GetDistinguisher() uint64 {
	if x != nil {
		return x.Distinguisher
	}
	return 0
}

func (x *PeerId) GetAdjRibOut() bool {
	if x != nil {
		return x.AdjRibOut
	}
	return false
}

type Family struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Afi           uint32                 `protobuf:"varint,1,opt,name=afi,proto3" json:"afi,omitempty"`
	Safi          uint32                 `protobuf:"varint,2,opt,name=safi,proto3" json:"safi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Family) Reset() {
	*x = Family{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Family) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Family) ProtoMessage() {}

func (x *Family) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Family.ProtoReflect.Descriptor instead.
func (*Family) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{3}
}

func (x *Family) GetAfi() uint32 {
	if x != nil {
		return x.Afi
	}
	return 0
}

func (x *Family) GetSafi() uint32 {
	if x != nil {
		return x.Safi
	}
	return 0
}

type Prefix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`                // CIDR text, e.g. "10.0.0.0/24"
	PathId        uint32                 `protobuf:"varint,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"` // 0 when add-path not in use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Prefix) Reset() {
	*x = Prefix{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Prefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Prefix) ProtoMessage() {}

func (x *Prefix) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Prefix.ProtoReflect.Descriptor instead.
func (*Prefix) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{4}
}

func (x *Prefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *Prefix) GetPathId() uint32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

// VpnPrefix is one labeled, RD-scoped prefix from a vpn4 (RFC 4364) or lu4
// (RFC 8277) MP_REACH/MP_UNREACH NLRI.
type VpnPrefix struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Prefix string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`                // CIDR text, e.g. "10.0.0.0/24"
	PathId uint32                 `protobuf:"varint,2,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"` // 0 when add-path not in use
	Rd     string                 `protobuf:"bytes,3,opt,name=rd,proto3" json:"rd,omitempty"`                        // RFC 4364 §4.2 text: "65000:100", "10.0.0.1:1", "65536:1"
	// labels: MPLS label stack, top first, 20-bit values. On vpn_withdrawn,
	// 524288 is the RFC 3107/8277 withdraw sentinel (0x800000 on the wire,
	// bottom-of-stack bit clear), not a real label, and must be ignored --
	// but 524288 is ALSO a legal 20-bit label value (a genuine label of
	// 524288 is 0x800001, S bit set), so this field alone cannot distinguish
	// the two. Both are shifted (raw >> 4) identically by internal/bgp before
	// reaching this wire form; this layer forwards the parser's determination
	// verbatim rather than disambiguating it (see internal/bgp/nlri.go).
	Labels        []uint32 `protobuf:"varint,4,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnPrefix) Reset() {
	*x = VpnPrefix{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnPrefix) ProtoMessage() {}

func (x *VpnPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnPrefix.ProtoReflect.Descriptor instead.
func (*VpnPrefix) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{5}
}

func (x *VpnPrefix) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *VpnPrefix) GetPathId() uint32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *VpnPrefix) GetRd() string {
	if x != nil {
		return x.Rd
	}
	return ""
}

func (x *VpnPrefix) GetLabels() []uint32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

// EvpnRoute is one EVPN NLRI (RFC 7432 §7). Route types 2, 3 and 5 are decoded
// into typed fields; every other type is carried in raw with route_type tagged.
type EvpnRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteType     uint32                 `protobuf:"varint,1,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	Rd            string                 `protobuf:"bytes,2,opt,name=rd,proto3" json:"rd,omitempty"`
	PathId        uint32                 `protobuf:"varint,3,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	Mac           string                 `protobuf:"bytes,4,opt,name=mac,proto3" json:"mac,omitempty"`                                          // type 2, "aa:bb:cc:dd:ee:ff"
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`                                            // type 2, may be empty (MAC-only advertisement)
	OriginatingIp string                 `protobuf:"bytes,6,opt,name=originating_ip,json=originatingIp,proto3" json:"originating_ip,omitempty"` // type 3
	Prefix        string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`                                    // type 5, CIDR text
	GatewayIp     string                 `protobuf:"bytes,8,opt,name=gateway_ip,json=gatewayIp,proto3" json:"gateway_ip,omitempty"`             // type 5
	EthernetTag   uint32                 `protobuf:"varint,9,opt,name=ethernet_tag,json=ethernetTag,proto3" json:"ethernet_tag,omitempty"`
	Esi           string                 `protobuf:"bytes,10,opt,name=esi,proto3" json:"esi,omitempty"` // 10-byte Ethernet Segment Identifier, hex
	// labels holds the RAW 24-bit value from the NLRI's label field. Its meaning
	// depends on encapsulation (RFC 9012 / RFC 8365): an MPLS label is 20 bits in
	// the high end, a VXLAN VNI is the full 24 bits unshifted. This package does
	// not parse the Encapsulation Extended Community, so it does not guess --
	// shifting unconditionally would silently halve every VNI on a VXLAN fabric.
	Labels        []uint32 `protobuf:"varint,11,rep,packed,name=labels,proto3" json:"labels,omitempty"`
	Raw           []byte   `protobuf:"bytes,12,opt,name=raw,proto3" json:"raw,omitempty"` // set when route_type is not decoded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvpnRoute) Reset() {
	*x = EvpnRoute{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvpnRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvpnRoute) ProtoMessage() {}

func (x *EvpnRoute) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvpnRoute.ProtoReflect.Descriptor instead.
func (*EvpnRoute) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{6}
}

func (x *EvpnRoute) GetRouteType() uint32 {
	if x != nil {
		return x.RouteType
	}
	return 0
}

func (x *EvpnRoute) GetRd() string {
	if x != nil {
		return x.Rd
	}
	return ""
}

func (x *EvpnRoute) GetPathId() uint32 {
	if x != nil {
		return x.PathId
	}
	return 0
}

func (x *EvpnRoute) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *EvpnRoute) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *EvpnRoute) GetOriginatingIp() string {
	if x != nil {
		return x.OriginatingIp
	}
	return ""
}

func (x *EvpnRoute) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *EvpnRoute) GetGatewayIp() string {
	if x != nil {
		return x.GatewayIp
	}
	return ""
}

func (x *EvpnRoute) GetEthernetTag() uint32 {
	if x != nil {
		return x.EthernetTag
	}
	return 0
}

func (x *EvpnRoute) GetEsi() string {
	if x != nil {
		return x.Esi
	}
	return ""
}

func (x *EvpnRoute) GetLabels() []uint32 {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EvpnRoute) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type AsPathSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // 1=SET 2=SEQUENCE
	Asns          []uint32               `protobuf:"varint,2,rep,packed,name=asns,proto3" json:"asns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsPathSegment) Reset() {
	*x = AsPathSegment{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsPathSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsPathSegment) ProtoMessage() {}

func (x *AsPathSegment) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsPathSegment.ProtoReflect.Descriptor instead.
func (*AsPathSegment) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{7}
}

func (x *AsPathSegment) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *AsPathSegment) GetAsns() []uint32 {
	if x != nil {
		return x.Asns
	}
	return nil
}

type Aggregator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregator) Reset() {
	*x = Aggregator{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregator) ProtoMessage() {}

func (x *Aggregator) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregator.ProtoReflect.Descriptor instead.
func (*Aggregator) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{8}
}

func (x *Aggregator) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *Aggregator) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LargeCommunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalAdmin   uint32                 `protobuf:"varint,1,opt,name=global_admin,json=globalAdmin,proto3" json:"global_admin,omitempty"`
	LocalData1    uint32                 `protobuf:"varint,2,opt,name=local_data1,json=localData1,proto3" json:"local_data1,omitempty"`
	LocalData2    uint32                 `protobuf:"varint,3,opt,name=local_data2,json=localData2,proto3" json:"local_data2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LargeCommunity) Reset() {
	*x = LargeCommunity{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LargeCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LargeCommunity) ProtoMessage() {}

func (x *LargeCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LargeCommunity.ProtoReflect.Descriptor instead.
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{9}
}

func (x *LargeCommunity) GetGlobalAdmin() uint32 {
	if x != nil {
		return x.GlobalAdmin
	}
	return 0
}

func (x *LargeCommunity) GetLocalData1() uint32 {
	if x != nil {
		return x.LocalData1
	}
	return 0
}

func (x *LargeCommunity) GetLocalData2() uint32 {
	if x != nil {
		return x.LocalData2
	}
	return 0
}

// ExtCommunity is one 8-byte extended community (RFC 4360 §3). The value's
// shape comes from the high-order type octet, not the subtype, so an
// unrecognized subtype still decodes structurally.
type ExtCommunity struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Type    uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"` // high octet, transitive bit included
	SubType uint32                 `protobuf:"varint,2,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	// value renders the six bytes after type and sub_type: "65000:100" for
	// an AS-specific community, "10.0.0.1:5" for an IPv4-specific one,
	// "52:31:d4:03:1b:08" for an EVPN router MAC, else "0x" and 12 hex digits.
	Value         string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Raw           []byte `protobuf:"bytes,4,opt,name=raw,proto3" json:"raw,omitempty"` // always the 8 wire bytes, decoded or not
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtCommunity) Reset() {
	*x = ExtCommunity{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtCommunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtCommunity) ProtoMessage() {}

func (x *ExtCommunity) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtCommunity.ProtoReflect.Descriptor instead.
func (*ExtCommunity) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{10}
}

func (x *ExtCommunity) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ExtCommunity) GetSubType() uint32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *ExtCommunity) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ExtCommunity) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type UnknownAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnknownAttr) Reset() {
	*x = UnknownAttr{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnknownAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnknownAttr) ProtoMessage() {}

func (x *UnknownAttr) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnknownAttr.ProtoReflect.Descriptor instead.
func (*UnknownAttr) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{11}
}

func (x *UnknownAttr) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UnknownAttr) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *UnknownAttr) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PathAttributes struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Origin              uint32                 `protobuf:"varint,1,opt,name=origin,proto3" json:"origin,omitempty"` // 0=IGP 1=EGP 2=INCOMPLETE
	AsPath              []*AsPathSegment       `protobuf:"bytes,2,rep,name=as_path,json=asPath,proto3" json:"as_path,omitempty"`
	NextHop             string                 `protobuf:"bytes,3,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Med                 *uint32                `protobuf:"varint,4,opt,name=med,proto3,oneof" json:"med,omitempty"`
	LocalPref           *uint32                `protobuf:"varint,5,opt,name=local_pref,json=localPref,proto3,oneof" json:"local_pref,omitempty"`
	AtomicAggregate     bool                   `protobuf:"varint,6,opt,name=atomic_aggregate,json=atomicAggregate,proto3" json:"atomic_aggregate,omitempty"`
	Aggregator          *Aggregator            `protobuf:"bytes,7,opt,name=aggregator,proto3" json:"aggregator,omitempty"`
	Communities         []uint32               `protobuf:"varint,8,rep,packed,name=communities,proto3" json:"communities,omitempty"`
	ExtendedCommunities []*ExtCommunity        `protobuf:"bytes,11,rep,name=extended_communities,json=extendedCommunities,proto3" json:"extended_communities,omitempty"`
	LargeCommunities    []*LargeCommunity      `protobuf:"bytes,10,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	Unknown             []*UnknownAttr         `protobuf:"bytes,15,rep,name=unknown,proto3" json:"unknown,omitempty"` // lossless fallback
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PathAttributes) Reset() {
	*x = PathAttributes{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathAttributes) ProtoMessage() {}

func (x *PathAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathAttributes.ProtoReflect.Descriptor instead.
func (*PathAttributes) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{12}
}

func (x *PathAttributes) GetOrigin() uint32 {
	if x != nil {
		return x.Origin
	}
	return 0
}

func (x *PathAttributes) GetAsPath() []*AsPathSegment {
	if x != nil {
		return x.AsPath
	}
	return nil
}

func (x *PathAttributes) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *PathAttributes) GetMed() uint32 {
	if x != nil && x.Med != nil {
		return *x.Med
	}
	return 0
}

func (x *PathAttributes) GetLocalPref() uint32 {
	if x != nil && x.LocalPref != nil {
		return *x.LocalPref
	}
	return 0
}

func (x *PathAttributes) GetAtomicAggregate() bool {
	if x != nil {
		return x.AtomicAggregate
	}
	return false
}

func (x *PathAttributes) GetAggregator() *Aggregator {
	if x != nil {
		return x.Aggregator
	}
	return nil
}

func (x *PathAttributes) GetCommunities() []uint32 {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *PathAttributes) GetExtendedCommunities() []*ExtCommunity {
	if x != nil {
		return x.ExtendedCommunities
	}
	return nil
}

func (x *PathAttributes) GetLargeCommunities() []*LargeCommunity {
	if x != nil {
		return x.LargeCommunities
	}
	return nil
}

func (x *PathAttributes) GetUnknown() []*UnknownAttr {
	if x != nil {
		return x.Unknown
	}
	return nil
}

type RouteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Attrs         *PathAttributes        `protobuf:"bytes,2,opt,name=attrs,proto3" json:"attrs,omitempty"`
	Announced     []*Prefix              `protobuf:"bytes,3,rep,name=announced,proto3" json:"announced,omitempty"`
	Withdrawn     []*Prefix              `protobuf:"bytes,4,rep,name=withdrawn,proto3" json:"withdrawn,omitempty"`
	EndOfRib      bool                   `protobuf:"varint,5,opt,name=end_of_rib,json=endOfRib,proto3" json:"end_of_rib,omitempty"`
	RawReach      []byte                 `protobuf:"bytes,6,opt,name=raw_reach,json=rawReach,proto3" json:"raw_reach,omitempty"`       // MP_REACH attr value bytes
	RawUnreach    []byte                 `protobuf:"bytes,7,opt,name=raw_unreach,json=rawUnreach,proto3" json:"raw_unreach,omitempty"` // MP_UNREACH attr value bytes
	VpnAnnounced  []*VpnPrefix           `protobuf:"bytes,8,rep,name=vpn_announced,json=vpnAnnounced,proto3" json:"vpn_announced,omitempty"`
	VpnWithdrawn  []*VpnPrefix           `protobuf:"bytes,9,rep,name=vpn_withdrawn,json=vpnWithdrawn,proto3" json:"vpn_withdrawn,omitempty"`
	EvpnAnnounced []*EvpnRoute           `protobuf:"bytes,10,rep,name=evpn_announced,json=evpnAnnounced,proto3" json:"evpn_announced,omitempty"`
	EvpnWithdrawn []*EvpnRoute           `protobuf:"bytes,11,rep,name=evpn_withdrawn,json=evpnWithdrawn,proto3" json:"evpn_withdrawn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteEvent) Reset() {
	*x = RouteEvent{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteEvent) ProtoMessage() {}

func (x *RouteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteEvent.ProtoReflect.Descriptor instead.
func (*RouteEvent) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{13}
}

func (x *RouteEvent) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

func (x *RouteEvent) GetAttrs() *PathAttributes {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *RouteEvent) GetAnnounced() []*Prefix {
	if x != nil {
		return x.Announced
	}
	return nil
}

func (x *RouteEvent) GetWithdrawn() []*Prefix {
	if x != nil {
		return x.Withdrawn
	}
	return nil
}

func (x *RouteEvent) GetEndOfRib() bool {
	if x != nil {
		return x.EndOfRib
	}
	return false
}

func (x *RouteEvent) GetRawReach() []byte {
	if x != nil {
		return x.RawReach
	}
	return nil
}

func (x *RouteEvent) GetRawUnreach() []byte {
	if x != nil {
		return x.RawUnreach
	}
	return nil
}

func (x *RouteEvent) GetVpnAnnounced() []*VpnPrefix {
	if x != nil {
		return x.VpnAnnounced
	}
	return nil
}

func (x *RouteEvent) GetVpnWithdrawn() []*VpnPrefix {
	if x != nil {
		return x.VpnWithdrawn
	}
	return nil
}

func (x *RouteEvent) GetEvpnAnnounced() []*EvpnRoute {
	if x != nil {
		return x.EvpnAnnounced
	}
	return nil
}

func (x *RouteEvent) GetEvpnWithdrawn() []*EvpnRoute {
	if x != nil {
		return x.EvpnWithdrawn
	}
	return nil
}

// LsNodeDescriptor identifies one BGP-LS node (RFC 9552 §5.2.1.4). Every
// field is part of the identity: a router-id is unique only within an AS and
// area, so matching on it alone can attach a link to the wrong node.
type LsNodeDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asn           uint32                 `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	BgplsId       uint32                 `protobuf:"varint,2,opt,name=bgpls_id,json=bgplsId,proto3" json:"bgpls_id,omitempty"`
	Area          uint32                 `protobuf:"varint,3,opt,name=area,proto3" json:"area,omitempty"`
	RouterId      []byte                 `protobuf:"bytes,4,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"` // 4 bytes for OSPF, 6/7 for IS-IS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsNodeDescriptor) Reset() {
	*x = LsNodeDescriptor{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsNodeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNodeDescriptor) ProtoMessage() {}

func (x *LsNodeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNodeDescriptor.ProtoReflect.Descriptor instead.
func (*LsNodeDescriptor) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{14}
}

func (x *LsNodeDescriptor) GetAsn() uint32 {
	if x != nil {
		return x.Asn
	}
	return 0
}

func (x *LsNodeDescriptor) GetBgplsId() uint32 {
	if x != nil {
		return x.BgplsId
	}
	return 0
}

func (x *LsNodeDescriptor) GetArea() uint32 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *LsNodeDescriptor) GetRouterId() []byte {
	if x != nil {
		return x.RouterId
	}
	return nil
}

type LsNode struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Protocol     uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // RFC 9552 protocol-id
	Identifier   uint64                 `protobuf:"varint,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Local        *LsNodeDescriptor      `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	IsWithdraw   bool                   `protobuf:"varint,4,opt,name=is_withdraw,json=isWithdraw,proto3" json:"is_withdraw,omitempty"`
	Name         string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	SrgbBase     uint32                 `protobuf:"varint,6,opt,name=srgb_base,json=srgbBase,proto3" json:"srgb_base,omitempty"`
	SrgbSize     uint32                 `protobuf:"varint,7,opt,name=srgb_size,json=srgbSize,proto3" json:"srgb_size,omitempty"`
	SrlbBase     uint32                 `protobuf:"varint,8,opt,name=srlb_base,json=srlbBase,proto3" json:"srlb_base,omitempty"`
	SrlbSize     uint32                 `protobuf:"varint,9,opt,name=srlb_size,json=srlbSize,proto3" json:"srlb_size,omitempty"`
	SrAlgorithms []uint32               `protobuf:"varint,10,rep,packed,name=sr_algorithms,json=srAlgorithms,proto3" json:"sr_algorithms,omitempty"`
	RouterIdV4   []byte                 `protobuf:"bytes,11,opt,name=router_id_v4,json=routerIdV4,proto3" json:"router_id_v4,omitempty"`
	// unknown_tlvs holds TLVs from THIS node's own Node NLRI (including its
	// node descriptor's nested sub-TLVs) that this build does not recognize
	// -- distinct from LsEvent.unknown_tlvs, which is the
	// shared BGP-LS Attribute's unknown TLVs (one attribute per UPDATE, RFC
	// 9552 §5.3, so it is not per-node). sink/rows.go merges both into one
	// ls_nodes.unknown_tlvs column, since the DDL has only one such column and
	// "which container did an unrecognized TLV come from" is not information a
	// topology consumer needs to act on.
	UnknownTlvs   map[uint32][]byte `protobuf:"bytes,12,rep,name=unknown_tlvs,json=unknownTlvs,proto3" json:"unknown_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsNode) Reset() {
	*x = LsNode{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsNode) ProtoMessage() {}

func (x *LsNode) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsNode.ProtoReflect.Descriptor instead.
func (*LsNode) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{15}
}

func (x *LsNode) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *LsNode) GetIdentifier() uint64 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *LsNode) GetLocal() *LsNodeDescriptor {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *LsNode) GetIsWithdraw() bool {
	if x != nil {
		return x.IsWithdraw
	}
	return false
}

func (x *LsNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LsNode) GetSrgbBase() uint32 {
	if x != nil {
		return x.SrgbBase
	}
	return 0
}

func (x *LsNode) GetSrgbSize() uint32 {
	if x != nil {
		return x.SrgbSize
	}
	return 0
}

func (x *LsNode) GetSrlbBase() uint32 {
	if x != nil {
		return x.SrlbBase
	}
	return 0
}

func (x *LsNode) GetSrlbSize() uint32 {
	if x != nil {
		return x.SrlbSize
	}
	return 0
}

func (x *LsNode) GetSrAlgorithms() []uint32 {
	if x != nil {
		return x.SrAlgorithms
	}
	return nil
}

func (x *LsNode) GetRouterIdV4() []byte {
	if x != nil {
		return x.RouterIdV4
	}
	return nil
}

func (x *LsNode) GetUnknownTlvs() map[uint32][]byte {
	if x != nil {
		return x.UnknownTlvs
	}
	return nil
}

type LsLink struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Protocol     uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Identifier   uint64                 `protobuf:"varint,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Local        *LsNodeDescriptor      `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	Remote       *LsNodeDescriptor      `protobuf:"bytes,4,opt,name=remote,proto3" json:"remote,omitempty"`
	LocalIfaddr  []byte                 `protobuf:"bytes,5,opt,name=local_ifaddr,json=localIfaddr,proto3" json:"local_ifaddr,omitempty"`
	RemoteIfaddr []byte                 `protobuf:"bytes,6,opt,name=remote_ifaddr,json=remoteIfaddr,proto3" json:"remote_ifaddr,omitempty"`
	LinkLocalId  uint32                 `protobuf:"varint,7,opt,name=link_local_id,json=linkLocalId,proto3" json:"link_local_id,omitempty"`
	LinkRemoteId uint32                 `protobuf:"varint,8,opt,name=link_remote_id,json=linkRemoteId,proto3" json:"link_remote_id,omitempty"`
	IsWithdraw   bool                   `protobuf:"varint,9,opt,name=is_withdraw,json=isWithdraw,proto3" json:"is_withdraw,omitempty"`
	// Repeated, not scalar: RFC 9085 2.2.1 permits several Adjacency SID TLVs
	// on one link, and protected/unprotected pairs are ordinary in SR-MPLS. A
	// scalar keeps only the last and loses half the SR data per link.
	AdjSids      []*LsAdjacencySid `protobuf:"bytes,10,rep,name=adj_sids,json=adjSids,proto3" json:"adj_sids,omitempty"`
	TeMetric     uint32            `protobuf:"varint,11,opt,name=te_metric,json=teMetric,proto3" json:"te_metric,omitempty"`
	IgpMetric    uint32            `protobuf:"varint,12,opt,name=igp_metric,json=igpMetric,proto3" json:"igp_metric,omitempty"`
	AdminGroup   uint32            `protobuf:"varint,13,opt,name=admin_group,json=adminGroup,proto3" json:"admin_group,omitempty"`
	MaxBandwidth float32           `protobuf:"fixed32,14,opt,name=max_bandwidth,json=maxBandwidth,proto3" json:"max_bandwidth,omitempty"`
	// unknown_tlvs: see LsNode.unknown_tlvs -- same rationale, this link's own
	// Link NLRI TLVs (including local/remote node descriptor sub-TLVs) rather
	// than the shared BGP-LS Attribute's.
	UnknownTlvs   map[uint32][]byte `protobuf:"bytes,15,rep,name=unknown_tlvs,json=unknownTlvs,proto3" json:"unknown_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsLink) Reset() {
	*x = LsLink{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsLink) ProtoMessage() {}

func (x *LsLink) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsLink.ProtoReflect.Descriptor instead.
func (*LsLink) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{16}
}

func (x *LsLink) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *LsLink) GetIdentifier() uint64 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *LsLink) GetLocal() *LsNodeDescriptor {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *LsLink) GetRemote() *LsNodeDescriptor {
	if x != nil {
		return x.Remote
	}
	return nil
}

func (x *LsLink) GetLocalIfaddr() []byte {
	if x != nil {
		return x.LocalIfaddr
	}
	return nil
}

func (x *LsLink) GetRemoteIfaddr() []byte {
	if x != nil {
		return x.RemoteIfaddr
	}
	return nil
}

func (x *LsLink) GetLinkLocalId() uint32 {
	if x != nil {
		return x.LinkLocalId
	}
	return 0
}

func (x *LsLink) GetLinkRemoteId() uint32 {
	if x != nil {
		return x.LinkRemoteId
	}
	return 0
}

func (x *LsLink) GetIsWithdraw() bool {
	if x != nil {
		return x.IsWithdraw
	}
	return false
}

func (x *LsLink) GetAdjSids() []*LsAdjacencySid {
	if x != nil {
		return x.AdjSids
	}
	return nil
}

func (x *LsLink) GetTeMetric() uint32 {
	if x != nil {
		return x.TeMetric
	}
	return 0
}

func (x *LsLink) GetIgpMetric() uint32 {
	if x != nil {
		return x.IgpMetric
	}
	return 0
}

func (x *LsLink) GetAdminGroup() uint32 {
	if x != nil {
		return x.AdminGroup
	}
	return 0
}

func (x *LsLink) GetMaxBandwidth() float32 {
	if x != nil {
		return x.MaxBandwidth
	}
	return 0
}

func (x *LsLink) GetUnknownTlvs() map[uint32][]byte {
	if x != nil {
		return x.UnknownTlvs
	}
	return nil
}

// LsPrefix is a Topology Prefix NLRI (RFC 9552 5.2.3) with its prefix
// attributes (RFC 9085 2.3) -- IPv4 (NLRI type 3) and IPv6 (type 4) both,
// since 2026-09-01. One message carries both because RFC 9552 gives the two
// types identical descriptors and prefix is a text field that carries its
// own family; nothing here needs to say which type a row came from. Separate from LsNode and LsLink for the reason
// that keeps those two apart: a prefix is a different
// object with a different identity, and folding it into either would make one
// message's fields meaningless for most of its rows.
type LsPrefix struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Protocol   uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Identifier uint64                 `protobuf:"varint,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// local is the node advertising reachability to this prefix. It is the same
	// descriptor a Node NLRI carries, which is what lets ClickHouse derive the
	// same node_key for both and join a prefix to its node.
	Local         *LsNodeDescriptor `protobuf:"bytes,3,opt,name=local,proto3" json:"local,omitempty"`
	Prefix        []byte            `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"` // packed address bytes, 4 for IPv4
	PrefixLen     uint32            `protobuf:"varint,5,opt,name=prefix_len,json=prefixLen,proto3" json:"prefix_len,omitempty"`
	OspfRouteType uint32            `protobuf:"varint,6,opt,name=ospf_route_type,json=ospfRouteType,proto3" json:"ospf_route_type,omitempty"` // TLV 264: 1 intra-area, 2 inter-area, ...
	IsWithdraw    bool              `protobuf:"varint,7,opt,name=is_withdraw,json=isWithdraw,proto3" json:"is_withdraw,omitempty"`
	// prefix_sid carries the node SID. has_prefix_sid distinguishes an absent
	// TLV from a legitimately-zero index, and prefix_sid_flags changes what the
	// value MEANS -- with V and L set it is an absolute label rather than an
	// index into the SRGB.
	PrefixSid       uint32 `protobuf:"varint,8,opt,name=prefix_sid,json=prefixSid,proto3" json:"prefix_sid,omitempty"`
	PrefixSidFlags  uint32 `protobuf:"varint,9,opt,name=prefix_sid_flags,json=prefixSidFlags,proto3" json:"prefix_sid_flags,omitempty"`
	HasPrefixSid    bool   `protobuf:"varint,10,opt,name=has_prefix_sid,json=hasPrefixSid,proto3" json:"has_prefix_sid,omitempty"`
	PrefixMetric    uint32 `protobuf:"varint,11,opt,name=prefix_metric,json=prefixMetric,proto3" json:"prefix_metric,omitempty"`
	PrefixAttrFlags uint32 `protobuf:"varint,12,opt,name=prefix_attr_flags,json=prefixAttrFlags,proto3" json:"prefix_attr_flags,omitempty"` // TLV 1170
	// unknown_tlvs: see LsNode.unknown_tlvs -- this prefix's own NLRI TLVs.
	UnknownTlvs   map[uint32][]byte `protobuf:"bytes,13,rep,name=unknown_tlvs,json=unknownTlvs,proto3" json:"unknown_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsPrefix) Reset() {
	*x = LsPrefix{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsPrefix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsPrefix) ProtoMessage() {}

func (x *LsPrefix) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsPrefix.ProtoReflect.Descriptor instead.
func (*LsPrefix) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{17}
}

func (x *LsPrefix) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *LsPrefix) GetIdentifier() uint64 {
	if x != nil {
		return x.Identifier
	}
	return 0
}

func (x *LsPrefix) GetLocal() *LsNodeDescriptor {
	if x != nil {
		return x.Local
	}
	return nil
}

func (x *LsPrefix) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *LsPrefix) GetPrefixLen() uint32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *LsPrefix) GetOspfRouteType() uint32 {
	if x != nil {
		return x.OspfRouteType
	}
	return 0
}

func (x *LsPrefix) GetIsWithdraw() bool {
	if x != nil {
		return x.IsWithdraw
	}
	return false
}

func (x *LsPrefix) GetPrefixSid() uint32 {
	if x != nil {
		return x.PrefixSid
	}
	return 0
}

func (x *LsPrefix) GetPrefixSidFlags() uint32 {
	if x != nil {
		return x.PrefixSidFlags
	}
	return 0
}

func (x *LsPrefix) GetHasPrefixSid() bool {
	if x != nil {
		return x.HasPrefixSid
	}
	return false
}

func (x *LsPrefix) GetPrefixMetric() uint32 {
	if x != nil {
		return x.PrefixMetric
	}
	return 0
}

func (x *LsPrefix) GetPrefixAttrFlags() uint32 {
	if x != nil {
		return x.PrefixAttrFlags
	}
	return 0
}

func (x *LsPrefix) GetUnknownTlvs() map[uint32][]byte {
	if x != nil {
		return x.UnknownTlvs
	}
	return nil
}

type LsAdjacencySid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           uint32                 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsAdjacencySid) Reset() {
	*x = LsAdjacencySid{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsAdjacencySid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsAdjacencySid) ProtoMessage() {}

func (x *LsAdjacencySid) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsAdjacencySid.ProtoReflect.Descriptor instead.
func (*LsAdjacencySid) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{18}
}

func (x *LsAdjacencySid) GetSid() uint32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *LsAdjacencySid) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *LsAdjacencySid) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type LsEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Family      *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Attrs       *PathAttributes        `protobuf:"bytes,2,opt,name=attrs,proto3" json:"attrs,omitempty"`
	RawReach    []byte                 `protobuf:"bytes,3,opt,name=raw_reach,json=rawReach,proto3" json:"raw_reach,omitempty"`       // MP_REACH attr value bytes
	RawUnreach  []byte                 `protobuf:"bytes,4,opt,name=raw_unreach,json=rawUnreach,proto3" json:"raw_unreach,omitempty"` // MP_UNREACH attr value bytes
	Nodes       []*LsNode              `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links       []*LsLink              `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	UnknownTlvs map[uint32][]byte      `protobuf:"bytes,7,rep,name=unknown_tlvs,json=unknownTlvs,proto3" json:"unknown_tlvs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // BGP-LS attribute TLVs not decoded
	// end_of_rib mirrors RouteEvent.end_of_rib (RFC 4724 §2): an LS End-of-RIB
	// carries no NLRI at all, so without this field "the LS RIB finished
	// converging" was unrepresentable in ClickHouse -- bgp.Update.EndOfRIB was
	// already computed correctly, but LsEvent had nowhere to put it.
	EndOfRib      bool        `protobuf:"varint,8,opt,name=end_of_rib,json=endOfRib,proto3" json:"end_of_rib,omitempty"`
	Prefixes      []*LsPrefix `protobuf:"bytes,9,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LsEvent) Reset() {
	*x = LsEvent{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LsEvent) ProtoMessage() {}

func (x *LsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LsEvent.ProtoReflect.Descriptor instead.
func (*LsEvent) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{19}
}

func (x *LsEvent) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

func (x *LsEvent) GetAttrs() *PathAttributes {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *LsEvent) GetRawReach() []byte {
	if x != nil {
		return x.RawReach
	}
	return nil
}

func (x *LsEvent) GetRawUnreach() []byte {
	if x != nil {
		return x.RawUnreach
	}
	return nil
}

func (x *LsEvent) GetNodes() []*LsNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LsEvent) GetLinks() []*LsLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LsEvent) GetUnknownTlvs() map[uint32][]byte {
	if x != nil {
		return x.UnknownTlvs
	}
	return nil
}

func (x *LsEvent) GetEndOfRib() bool {
	if x != nil {
		return x.EndOfRib
	}
	return false
}

func (x *LsEvent) GetPrefixes() []*LsPrefix {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

type Capabilities struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FourByteAs      bool                   `protobuf:"varint,1,opt,name=four_byte_as,json=fourByteAs,proto3" json:"four_byte_as,omitempty"`
	AddpathFamilies []*Family              `protobuf:"bytes,2,rep,name=addpath_families,json=addpathFamilies,proto3" json:"addpath_families,omitempty"` // negotiated both directions
	MpFamilies      []*Family              `protobuf:"bytes,3,rep,name=mp_families,json=mpFamilies,proto3" json:"mp_families,omitempty"`
	// The NEGOTIATED Hold Time in seconds: the smaller of the two the
	// session's OPENs offered (RFC 4271 sec 4.2). Not a capability -- it is a
	// fixed OPEN body field -- but it is negotiated from the same pair of
	// messages and consumed by the same readers, so it travels with them.
	//
	// Zero is a VALUE: RFC 4271 says a hold time of 0 means the timer never
	// expires, i.e. keepalives are off for this session. Readers must keep
	// that apart from "no OPEN was observed", which is what hold_time_seen
	// below is for -- proto3 scalars cannot tell an unset 0 from a real one.
	HoldTime      uint32 `protobuf:"varint,4,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	HoldTimeSeen  bool   `protobuf:"varint,5,opt,name=hold_time_seen,json=holdTimeSeen,proto3" json:"hold_time_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{20}
}

func (x *Capabilities) GetFourByteAs() bool {
	if x != nil {
		return x.FourByteAs
	}
	return false
}

func (x *Capabilities) GetAddpathFamilies() []*Family {
	if x != nil {
		return x.AddpathFamilies
	}
	return nil
}

func (x *Capabilities) GetMpFamilies() []*Family {
	if x != nil {
		return x.MpFamilies
	}
	return nil
}

func (x *Capabilities) GetHoldTime() uint32 {
	if x != nil {
		return x.HoldTime
	}
	return 0
}

func (x *Capabilities) GetHoldTimeSeen() bool {
	if x != nil {
		return x.HoldTimeSeen
	}
	return false
}

type PeerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          PeerEvent_Kind         `protobuf:"varint,1,opt,name=kind,proto3,enum=vantage.v1.PeerEvent_Kind" json:"kind,omitempty"`
	LocalIp       string                 `protobuf:"bytes,2,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort     uint32                 `protobuf:"varint,3,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort    uint32                 `protobuf:"varint,4,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	SentOpen      []byte                 `protobuf:"bytes,5,opt,name=sent_open,json=sentOpen,proto3" json:"sent_open,omitempty"` // raw OPEN incl. BGP header, on record
	RecvOpen      []byte                 `protobuf:"bytes,6,opt,name=recv_open,json=recvOpen,proto3" json:"recv_open,omitempty"`
	Caps          *Capabilities          `protobuf:"bytes,7,opt,name=caps,proto3" json:"caps,omitempty"`
	DownReason    uint32                 `protobuf:"varint,8,opt,name=down_reason,json=downReason,proto3" json:"down_reason,omitempty"`
	DownData      []byte                 `protobuf:"bytes,9,opt,name=down_data,json=downData,proto3" json:"down_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerEvent) Reset() {
	*x = PeerEvent{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerEvent) ProtoMessage() {}

func (x *PeerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerEvent.ProtoReflect.Descriptor instead.
func (*PeerEvent) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{21}
}

func (x *PeerEvent) GetKind() PeerEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return PeerEvent_KIND_UNSPECIFIED
}

func (x *PeerEvent) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *PeerEvent) GetLocalPort() uint32 {
	if x != nil {
		return x.LocalPort
	}
	return 0
}

func (x *PeerEvent) GetRemotePort() uint32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

func (x *PeerEvent) GetSentOpen() []byte {
	if x != nil {
		return x.SentOpen
	}
	return nil
}

func (x *PeerEvent) GetRecvOpen() []byte {
	if x != nil {
		return x.RecvOpen
	}
	return nil
}

func (x *PeerEvent) GetCaps() *Capabilities {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *PeerEvent) GetDownReason() uint32 {
	if x != nil {
		return x.DownReason
	}
	return 0
}

func (x *PeerEvent) GetDownData() []byte {
	if x != nil {
		return x.DownData
	}
	return nil
}

type StatsEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Counters      map[uint32]uint64      `protobuf:"bytes,1,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // BMP stat TLV type -> value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsEvent) Reset() {
	*x = StatsEvent{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsEvent) ProtoMessage() {}

func (x *StatsEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsEvent.ProtoReflect.Descriptor instead.
func (*StatsEvent) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{22}
}

func (x *StatsEvent) GetCounters() map[uint32]uint64 {
	if x != nil {
		return x.Counters
	}
	return nil
}

type RawEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	BmpMsg     []byte                 `protobuf:"bytes,1,opt,name=bmp_msg,json=bmpMsg,proto3" json:"bmp_msg,omitempty"` // full original BMP message incl. common header
	ParseError string                 `protobuf:"bytes,2,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
	// mirrored distinguishes a message republished by mirror mode from one that
	// failed to parse. Both land on vantage.v1.raw.{router}; without this a
	// consumer can only infer the difference from parse_error being empty, which
	// is also true of Termination.
	Mirrored      bool `protobuf:"varint,3,opt,name=mirrored,proto3" json:"mirrored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawEvent) Reset() {
	*x = RawEvent{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawEvent) ProtoMessage() {}

func (x *RawEvent) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawEvent.ProtoReflect.Descriptor instead.
func (*RawEvent) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{23}
}

func (x *RawEvent) GetBmpMsg() []byte {
	if x != nil {
		return x.BmpMsg
	}
	return nil
}

func (x *RawEvent) GetParseError() string {
	if x != nil {
		return x.ParseError
	}
	return ""
}

func (x *RawEvent) GetMirrored() bool {
	if x != nil {
		return x.Mirrored
	}
	return false
}

// CollectorBeat is a collector saying it is alive. Every collector publishes
// one at startup, before it accepts a BMP session, and every 30 s after, on
// vantage.v1.stats.beat.{collector} (subjects.Beat). It names no router and
// no peer: its subject is the collector itself.
//
// started_at is when this collector PROCESS started, on the collector's own
// clock, captured before any session exists. session_id is now().UnixNano()
// on that same clock, so every session this process opens has an id at or
// above started_at, and every session an earlier process under the same
// collector_id opened has one below it. Readers take the newest started_at
// per collector as its epoch.
//
// The envelope's ts_collector is when this beat was built. It is kept for
// display only: readers decide liveness from the time the archive RECEIVED
// the beat, never from this clock, so a collector with a wrong clock cannot
// make itself stale or fresh.
type CollectorBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectorBeat) Reset() {
	*x = CollectorBeat{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorBeat) ProtoMessage() {}

func (x *CollectorBeat) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorBeat.ProtoReflect.Descriptor instead.
func (*CollectorBeat) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{24}
}

func (x *CollectorBeat) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type Envelope struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	CollectorId string                 `protobuf:"bytes,1,opt,name=collector_id,json=collectorId,proto3" json:"collector_id,omitempty"`
	Router      *RouterId              `protobuf:"bytes,2,opt,name=router,proto3" json:"router,omitempty"`
	Peer        *PeerId                `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	SessionId   uint64                 `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq         uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	TsRouter    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ts_router,json=tsRouter,proto3" json:"ts_router,omitempty"`
	TsCollector *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ts_collector,json=tsCollector,proto3" json:"ts_collector,omitempty"`
	RouterInfo  *RouterInfo            `protobuf:"bytes,8,opt,name=router_info,json=routerInfo,proto3" json:"router_info,omitempty"`
	ParseFlags  []ParseFlag            `protobuf:"varint,9,rep,packed,name=parse_flags,json=parseFlags,proto3,enum=vantage.v1.ParseFlag" json:"parse_flags,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Route
	//	*Envelope_Ls
	//	*Envelope_PeerEvent
	//	*Envelope_Stats
	//	*Envelope_Raw
	//	*Envelope_Beat
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_vantage_v1_vantage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_vantage_v1_vantage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_vantage_v1_vantage_proto_rawDescGZIP(), []int{25}
}

func (x *Envelope) GetCollectorId() string {
	if x != nil {
		return x.CollectorId
	}
	return ""
}

func (x *Envelope) GetRouter() *RouterId {
	if x != nil {
		return x.Router
	}
	return nil
}

func (x *Envelope) GetPeer() *PeerId {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *Envelope) GetSessionId() uint64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetTsRouter() *timestamppb.Timestamp {
	if x != nil {
		return x.TsRouter
	}
	return nil
}

func (x *Envelope) GetTsCollector() *timestamppb.Timestamp {
	if x != nil {
		return x.TsCollector
	}
	return nil
}

func (x *Envelope) GetRouterInfo() *RouterInfo {
	if x != nil {
		return x.RouterInfo
	}
	return nil
}

func (x *Envelope) GetParseFlags() []ParseFlag {
	if x != nil {
		return x.ParseFlags
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetRoute() *RouteEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Route); ok {
			return x.Route
		}
	}
	return nil
}

func (x *Envelope) GetLs() *LsEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ls); ok {
			return x.Ls
		}
	}
	return nil
}

func (x *Envelope) GetPeerEvent() *PeerEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PeerEvent); ok {
			return x.PeerEvent
		}
	}
	return nil
}

func (x *Envelope) GetStats() *StatsEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *Envelope) GetRaw() *RawEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

func (x *Envelope) GetBeat() *CollectorBeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Beat); ok {
			return x.Beat
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Route struct {
	Route *RouteEvent `protobuf:"bytes,10,opt,name=route,proto3,oneof"`
}

type Envelope_Ls struct {
	Ls *LsEvent `protobuf:"bytes,11,opt,name=ls,proto3,oneof"`
}

type Envelope_PeerEvent struct {
	PeerEvent *PeerEvent `protobuf:"bytes,12,opt,name=peer_event,json=peerEvent,proto3,oneof"`
}

type Envelope_Stats struct {
	Stats *StatsEvent `protobuf:"bytes,13,opt,name=stats,proto3,oneof"`
}

type Envelope_Raw struct {
	Raw *RawEvent `protobuf:"bytes,14,opt,name=raw,proto3,oneof"`
}

type Envelope_Beat struct {
	Beat *CollectorBeat `protobuf:"bytes,15,opt,name=beat,proto3,oneof"`
}

func (*Envelope_Route) isEnvelope_Payload() {}

func (*Envelope_Ls) isEnvelope_Payload() {}

func (*Envelope_PeerEvent) isEnvelope_Payload() {}

func (*Envelope_Stats) isEnvelope_Payload() {}

func (*Envelope_Raw) isEnvelope_Payload() {}

func (*Envelope_Beat) isEnvelope_Payload() {}

var File_vantage_v1_vantage_proto protoreflect.FileDescriptor

const file_vantage_v1_vantage_proto_rawDesc = "" +
	"\n" +
	"\x18vantage/v1/vantage.proto\x12\n" +
	"vantage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"5\n" +
	"\bRouterId\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x19\n" +
	"\bsys_name\x18\x02 \x01(\tR\asysName\"k\n" +
	"\n" +
	"RouterInfo\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1b\n" +
	"\tsys_descr\x18\x04 \x01(\tR\bsysDescr\"\xd2\x01\n" +
	"\x06PeerId\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.vantage.v1.PeerTypeR\x04type\x12\x1f\n" +
	"\vpost_policy\x18\x02 \x01(\bR\n" +
	"postPolicy\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x10\n" +
	"\x03asn\x18\x04 \x01(\rR\x03asn\x12\x15\n" +
	"\x06bgp_id\x18\x05 \x01(\tR\x05bgpId\x12$\n" +
	"\rdistinguisher\x18\x06 \x01(\x04R\rdistinguisher\x12\x1e\n" +
	"\vadj_rib_out\x18\a \x01(\bR\tadjRibOut\".\n" +
	"\x06Family\x12\x10\n" +
	"\x03afi\x18\x01 \x01(\rR\x03afi\x12\x12\n" +
	"\x04safi\x18\x02 \x01(\rR\x04safi\"9\n" +
	"\x06Prefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x17\n" +
	"\apath_id\x18\x02 \x01(\rR\x06pathId\"d\n" +
	"\tVpnPrefix\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x17\n" +
	"\apath_id\x18\x02 \x01(\rR\x06pathId\x12\x0e\n" +
	"\x02rd\x18\x03 \x01(\tR\x02rd\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\rR\x06labels\"\xb2\x02\n" +
	"\tEvpnRoute\x12\x1d\n" +
	"\n" +
	"route_type\x18\x01 \x01(\rR\trouteType\x12\x0e\n" +
	"\x02rd\x18\x02 \x01(\tR\x02rd\x12\x17\n" +
	"\apath_id\x18\x03 \x01(\rR\x06pathId\x12\x10\n" +
	"\x03mac\x18\x04 \x01(\tR\x03mac\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12%\n" +
	"\x0eoriginating_ip\x18\x06 \x01(\tR\roriginatingIp\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12\x1d\n" +
	"\n" +
	"gateway_ip\x18\b \x01(\tR\tgatewayIp\x12!\n" +
	"\fethernet_tag\x18\t \x01(\rR\vethernetTag\x12\x10\n" +
	"\x03esi\x18\n" +
	" \x01(\tR\x03esi\x12\x16\n" +
	"\x06labels\x18\v \x03(\rR\x06labels\x12\x10\n" +
	"\x03raw\x18\f \x01(\fR\x03raw\"7\n" +
	"\rAsPathSegment\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x12\n" +
	"\x04asns\x18\x02 \x03(\rR\x04asns\".\n" +
	"\n" +
	"Aggregator\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"u\n" +
	"\x0eLargeCommunity\x12!\n" +
	"\fglobal_admin\x18\x01 \x01(\rR\vglobalAdmin\x12\x1f\n" +
	"\vlocal_data1\x18\x02 \x01(\rR\n" +
	"localData1\x12\x1f\n" +
	"\vlocal_data2\x18\x03 \x01(\rR\n" +
	"localData2\"e\n" +
	"\fExtCommunity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x19\n" +
	"\bsub_type\x18\x02 \x01(\rR\asubType\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x10\n" +
	"\x03raw\x18\x04 \x01(\fR\x03raw\"M\n" +
	"\vUnknownAttr\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"\xae\x04\n" +
	"\x0ePathAttributes\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\rR\x06origin\x122\n" +
	"\aas_path\x18\x02 \x03(\v2\x19.vantage.v1.AsPathSegmentR\x06asPath\x12\x19\n" +
	"\bnext_hop\x18\x03 \x01(\tR\anextHop\x12\x15\n" +
	"\x03med\x18\x04 \x01(\rH\x00R\x03med\x88\x01\x01\x12\"\n" +
	"\n" +
	"local_pref\x18\x05 \x01(\rH\x01R\tlocalPref\x88\x01\x01\x12)\n" +
	"\x10atomic_aggregate\x18\x06 \x01(\bR\x0fatomicAggregate\x126\n" +
	"\n" +
	"aggregator\x18\a \x01(\v2\x16.vantage.v1.AggregatorR\n" +
	"aggregator\x12 \n" +
	"\vcommunities\x18\b \x03(\rR\vcommunities\x12K\n" +
	"\x14extended_communities\x18\v \x03(\v2\x18.vantage.v1.ExtCommunityR\x13extendedCommunities\x12G\n" +
	"\x11large_communities\x18\n" +
	" \x03(\v2\x1a.vantage.v1.LargeCommunityR\x10largeCommunities\x121\n" +
	"\aunknown\x18\x0f \x03(\v2\x17.vantage.v1.UnknownAttrR\aunknownB\x06\n" +
	"\x04_medB\r\n" +
	"\v_local_prefJ\x04\b\t\x10\n" +
	"R\x0fext_communities\"\x9e\x04\n" +
	"\n" +
	"RouteEvent\x12*\n" +
	"\x06family\x18\x01 \x01(\v2\x12.vantage.v1.FamilyR\x06family\x120\n" +
	"\x05attrs\x18\x02 \x01(\v2\x1a.vantage.v1.PathAttributesR\x05attrs\x120\n" +
	"\tannounced\x18\x03 \x03(\v2\x12.vantage.v1.PrefixR\tannounced\x120\n" +
	"\twithdrawn\x18\x04 \x03(\v2\x12.vantage.v1.PrefixR\twithdrawn\x12\x1c\n" +
	"\n" +
	"end_of_rib\x18\x05 \x01(\bR\bendOfRib\x12\x1b\n" +
	"\traw_reach\x18\x06 \x01(\fR\brawReach\x12\x1f\n" +
	"\vraw_unreach\x18\a \x01(\fR\n" +
	"rawUnreach\x12:\n" +
	"\rvpn_announced\x18\b \x03(\v2\x15.vantage.v1.VpnPrefixR\fvpnAnnounced\x12:\n" +
	"\rvpn_withdrawn\x18\t \x03(\v2\x15.vantage.v1.VpnPrefixR\fvpnWithdrawn\x12<\n" +
	"\x0eevpn_announced\x18\n" +
	" \x03(\v2\x15.vantage.v1.EvpnRouteR\revpnAnnounced\x12<\n" +
	"\x0eevpn_withdrawn\x18\v \x03(\v2\x15.vantage.v1.EvpnRouteR\revpnWithdrawn\"p\n" +
	"\x10LsNodeDescriptor\x12\x10\n" +
	"\x03asn\x18\x01 \x01(\rR\x03asn\x12\x19\n" +
	"\bbgpls_id\x18\x02 \x01(\rR\abgplsId\x12\x12\n" +
	"\x04area\x18\x03 \x01(\rR\x04area\x12\x1b\n" +
	"\trouter_id\x18\x04 \x01(\fR\brouterId\"\xf0\x03\n" +
	"\x06LsNode\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\x04R\n" +
	"identifier\x122\n" +
	"\x05local\x18\x03 \x01(\v2\x1c.vantage.v1.LsNodeDescriptorR\x05local\x12\x1f\n" +
	"\vis_withdraw\x18\x04 \x01(\bR\n" +
	"isWithdraw\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1b\n" +
	"\tsrgb_base\x18\x06 \x01(\rR\bsrgbBase\x12\x1b\n" +
	"\tsrgb_size\x18\a \x01(\rR\bsrgbSize\x12\x1b\n" +
	"\tsrlb_base\x18\b \x01(\rR\bsrlbBase\x12\x1b\n" +
	"\tsrlb_size\x18\t \x01(\rR\bsrlbSize\x12#\n" +
	"\rsr_algorithms\x18\n" +
	" \x03(\rR\fsrAlgorithms\x12 \n" +
	"\frouter_id_v4\x18\v \x01(\fR\n" +
	"routerIdV4\x12F\n" +
	"\funknown_tlvs\x18\f \x03(\v2#.vantage.v1.LsNode.UnknownTlvsEntryR\vunknownTlvs\x1a>\n" +
	"\x10UnknownTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xa2\x05\n" +
	"\x06LsLink\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\x04R\n" +
	"identifier\x122\n" +
	"\x05local\x18\x03 \x01(\v2\x1c.vantage.v1.LsNodeDescriptorR\x05local\x124\n" +
	"\x06remote\x18\x04 \x01(\v2\x1c.vantage.v1.LsNodeDescriptorR\x06remote\x12!\n" +
	"\flocal_ifaddr\x18\x05 \x01(\fR\vlocalIfaddr\x12#\n" +
	"\rremote_ifaddr\x18\x06 \x01(\fR\fremoteIfaddr\x12\"\n" +
	"\rlink_local_id\x18\a \x01(\rR\vlinkLocalId\x12$\n" +
	"\x0elink_remote_id\x18\b \x01(\rR\flinkRemoteId\x12\x1f\n" +
	"\vis_withdraw\x18\t \x01(\bR\n" +
	"isWithdraw\x125\n" +
	"\badj_sids\x18\n" +
	" \x03(\v2\x1a.vantage.v1.LsAdjacencySidR\aadjSids\x12\x1b\n" +
	"\tte_metric\x18\v \x01(\rR\bteMetric\x12\x1d\n" +
	"\n" +
	"igp_metric\x18\f \x01(\rR\tigpMetric\x12\x1f\n" +
	"\vadmin_group\x18\r \x01(\rR\n" +
	"adminGroup\x12#\n" +
	"\rmax_bandwidth\x18\x0e \x01(\x02R\fmaxBandwidth\x12F\n" +
	"\funknown_tlvs\x18\x0f \x03(\v2#.vantage.v1.LsLink.UnknownTlvsEntryR\vunknownTlvs\x1a>\n" +
	"\x10UnknownTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xc4\x04\n" +
	"\bLsPrefix\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1e\n" +
	"\n" +
	"identifier\x18\x02 \x01(\x04R\n" +
	"identifier\x122\n" +
	"\x05local\x18\x03 \x01(\v2\x1c.vantage.v1.LsNodeDescriptorR\x05local\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\fR\x06prefix\x12\x1d\n" +
	"\n" +
	"prefix_len\x18\x05 \x01(\rR\tprefixLen\x12&\n" +
	"\x0fospf_route_type\x18\x06 \x01(\rR\rospfRouteType\x12\x1f\n" +
	"\vis_withdraw\x18\a \x01(\bR\n" +
	"isWithdraw\x12\x1d\n" +
	"\n" +
	"prefix_sid\x18\b \x01(\rR\tprefixSid\x12(\n" +
	"\x10prefix_sid_flags\x18\t \x01(\rR\x0eprefixSidFlags\x12$\n" +
	"\x0ehas_prefix_sid\x18\n" +
	" \x01(\bR\fhasPrefixSid\x12#\n" +
	"\rprefix_metric\x18\v \x01(\rR\fprefixMetric\x12*\n" +
	"\x11prefix_attr_flags\x18\f \x01(\rR\x0fprefixAttrFlags\x12H\n" +
	"\funknown_tlvs\x18\r \x03(\v2%.vantage.v1.LsPrefix.UnknownTlvsEntryR\vunknownTlvs\x1a>\n" +
	"\x10UnknownTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"P\n" +
	"\x0eLsAdjacencySid\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\rR\x03sid\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\"\xd2\x03\n" +
	"\aLsEvent\x12*\n" +
	"\x06family\x18\x01 \x01(\v2\x12.vantage.v1.FamilyR\x06family\x120\n" +
	"\x05attrs\x18\x02 \x01(\v2\x1a.vantage.v1.PathAttributesR\x05attrs\x12\x1b\n" +
	"\traw_reach\x18\x03 \x01(\fR\brawReach\x12\x1f\n" +
	"\vraw_unreach\x18\x04 \x01(\fR\n" +
	"rawUnreach\x12(\n" +
	"\x05nodes\x18\x05 \x03(\v2\x12.vantage.v1.LsNodeR\x05nodes\x12(\n" +
	"\x05links\x18\x06 \x03(\v2\x12.vantage.v1.LsLinkR\x05links\x12G\n" +
	"\funknown_tlvs\x18\a \x03(\v2$.vantage.v1.LsEvent.UnknownTlvsEntryR\vunknownTlvs\x12\x1c\n" +
	"\n" +
	"end_of_rib\x18\b \x01(\bR\bendOfRib\x120\n" +
	"\bprefixes\x18\t \x03(\v2\x14.vantage.v1.LsPrefixR\bprefixes\x1a>\n" +
	"\x10UnknownTlvsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\xe7\x01\n" +
	"\fCapabilities\x12 \n" +
	"\ffour_byte_as\x18\x01 \x01(\bR\n" +
	"fourByteAs\x12=\n" +
	"\x10addpath_families\x18\x02 \x03(\v2\x12.vantage.v1.FamilyR\x0faddpathFamilies\x123\n" +
	"\vmp_families\x18\x03 \x03(\v2\x12.vantage.v1.FamilyR\n" +
	"mpFamilies\x12\x1b\n" +
	"\thold_time\x18\x04 \x01(\rR\bholdTime\x12$\n" +
	"\x0ehold_time_seen\x18\x05 \x01(\bR\fholdTimeSeen\"\x8a\x03\n" +
	"\tPeerEvent\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.vantage.v1.PeerEvent.KindR\x04kind\x12\x19\n" +
	"\blocal_ip\x18\x02 \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\x03 \x01(\rR\tlocalPort\x12\x1f\n" +
	"\vremote_port\x18\x04 \x01(\rR\n" +
	"remotePort\x12\x1b\n" +
	"\tsent_open\x18\x05 \x01(\fR\bsentOpen\x12\x1b\n" +
	"\trecv_open\x18\x06 \x01(\fR\brecvOpen\x12,\n" +
	"\x04caps\x18\a \x01(\v2\x18.vantage.v1.CapabilitiesR\x04caps\x12\x1f\n" +
	"\vdown_reason\x18\b \x01(\rR\n" +
	"downReason\x12\x1b\n" +
	"\tdown_data\x18\t \x01(\fR\bdownData\"L\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aKIND_UP\x10\x01\x12\r\n" +
	"\tKIND_DOWN\x10\x02\x12\x12\n" +
	"\x0eKIND_VIEW_LOST\x10\x03\"\x8b\x01\n" +
	"\n" +
	"StatsEvent\x12@\n" +
	"\bcounters\x18\x01 \x03(\v2$.vantage.v1.StatsEvent.CountersEntryR\bcounters\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"`\n" +
	"\bRawEvent\x12\x17\n" +
	"\abmp_msg\x18\x01 \x01(\fR\x06bmpMsg\x12\x1f\n" +
	"\vparse_error\x18\x02 \x01(\tR\n" +
	"parseError\x12\x1a\n" +
	"\bmirrored\x18\x03 \x01(\bR\bmirrored\"J\n" +
	"\rCollectorBeat\x129\n" +
	"\n" +
	"started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\"\xc2\x05\n" +
	"\bEnvelope\x12!\n" +
	"\fcollector_id\x18\x01 \x01(\tR\vcollectorId\x12,\n" +
	"\x06router\x18\x02 \x01(\v2\x14.vantage.v1.RouterIdR\x06router\x12&\n" +
	"\x04peer\x18\x03 \x01(\v2\x12.vantage.v1.PeerIdR\x04peer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\x04R\tsessionId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x127\n" +
	"\tts_router\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\btsRouter\x12=\n" +
	"\fts_collector\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vtsCollector\x127\n" +
	"\vrouter_info\x18\b \x01(\v2\x16.vantage.v1.RouterInfoR\n" +
	"routerInfo\x126\n" +
	"\vparse_flags\x18\t \x03(\x0e2\x15.vantage.v1.ParseFlagR\n" +
	"parseFlags\x12.\n" +
	"\x05route\x18\n" +
	" \x01(\v2\x16.vantage.v1.RouteEventH\x00R\x05route\x12%\n" +
	"\x02ls\x18\v \x01(\v2\x13.vantage.v1.LsEventH\x00R\x02ls\x126\n" +
	"\n" +
	"peer_event\x18\f \x01(\v2\x15.vantage.v1.PeerEventH\x00R\tpeerEvent\x12.\n" +
	"\x05stats\x18\r \x01(\v2\x16.vantage.v1.StatsEventH\x00R\x05stats\x12(\n" +
	"\x03raw\x18\x0e \x01(\v2\x14.vantage.v1.RawEventH\x00R\x03raw\x12/\n" +
	"\x04beat\x18\x0f \x01(\v2\x19.vantage.v1.CollectorBeatH\x00R\x04beatB\t\n" +
	"\apayload*\xf5\x02\n" +
	"\tParseFlag\x12\x1a\n" +
	"\x16PARSE_FLAG_UNSPECIFIED\x10\x00\x12$\n" +
	" PARSE_FLAG_TS_COLLECTOR_FALLBACK\x10\x01\x12 \n" +
	"\x1cPARSE_FLAG_ADDPATH_HEURISTIC\x10\x02\x12\"\n" +
	"\x1ePARSE_FLAG_ATTR_DISCARDED_7606\x10\x03\x12%\n" +
	"!PARSE_FLAG_TREAT_AS_WITHDRAW_7606\x10\x04\x12\x1f\n" +
	"\x1bPARSE_FLAG_VERSION_UNPARSED\x10\x05\x12\x1d\n" +
	"\x19PARSE_FLAG_UNKNOWN_FAMILY\x10\x06\x12\x1b\n" +
	"\x17PARSE_FLAG_CAPS_MISSING\x10\a\x12\x1b\n" +
	"\x17PARSE_FLAG_NLRI_UNTYPED\x10\b\x12 \n" +
	"\x1cPARSE_FLAG_LS_NLRI_UNDECODED\x10\t\x12\x1d\n" +
	"\x19PARSE_FLAG_LS_TLV_UNKNOWN\x10\n" +
	"*^\n" +
	"\bPeerType\x12\x14\n" +
	"\x10PEER_TYPE_GLOBAL\x10\x00\x12\x10\n" +
	"\fPEER_TYPE_RD\x10\x01\x12\x13\n" +
	"\x0fPEER_TYPE_LOCAL\x10\x02\x12\x15\n" +
	"\x11PEER_TYPE_LOC_RIB\x10\x03B\x9e\x01\n" +
	"\x0ecom.vantage.v1B\fVantageProtoP\x01Z5github.com/jp2195/vantage/schema/vantage/v1;vantagev1\xa2\x02\x03VXX\xaa\x02\n" +
	"Vantage.V1\xca\x02\n" +
	"Vantage\\V1\xe2\x02\x16Vantage\\V1\\GPBMetadata\xea\x02\vVantage::V1b\x06proto3"

var (
	file_vantage_v1_vantage_proto_rawDescOnce sync.Once
	file_vantage_v1_vantage_proto_rawDescData []byte
)

func file_vantage_v1_vantage_proto_rawDescGZIP() []byte {
	file_vantage_v1_vantage_proto_rawDescOnce.Do(func() {
		file_vantage_v1_vantage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vantage_v1_vantage_proto_rawDesc), len(file_vantage_v1_vantage_proto_rawDesc)))
	})
	return file_vantage_v1_vantage_proto_rawDescData
}

var file_vantage_v1_vantage_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_vantage_v1_vantage_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_vantage_v1_vantage_proto_goTypes = []any{
	(ParseFlag)(0),                // 0: vantage.v1.ParseFlag
	(PeerType)(0),                 // 1: vantage.v1.PeerType
	(PeerEvent_Kind)(0),           // 2: vantage.v1.PeerEvent.Kind
	(*RouterId)(nil),              // 3: vantage.v1.RouterId
	(*RouterInfo)(nil),            // 4: vantage.v1.RouterInfo
	(*PeerId)(nil),                // 5: vantage.v1.PeerId
	(*Family)(nil),                // 6: vantage.v1.Family
	(*Prefix)(nil),                // 7: vantage.v1.Prefix
	(*VpnPrefix)(nil),             // 8: vantage.v1.VpnPrefix
	(*EvpnRoute)(nil),             // 9: vantage.v1.EvpnRoute
	(*AsPathSegment)(nil),         // 10: vantage.v1.AsPathSegment
	(*Aggregator)(nil),            // 11: vantage.v1.Aggregator
	(*LargeCommunity)(nil),        // 12: vantage.v1.LargeCommunity
	(*ExtCommunity)(nil),          // 13: vantage.v1.ExtCommunity
	(*UnknownAttr)(nil),           // 14: vantage.v1.UnknownAttr
	(*PathAttributes)(nil),        // 15: vantage.v1.PathAttributes
	(*RouteEvent)(nil),            // 16: vantage.v1.RouteEvent
	(*LsNodeDescriptor)(nil),      // 17: vantage.v1.LsNodeDescriptor
	(*LsNode)(nil),                // 18: vantage.v1.LsNode
	(*LsLink)(nil),                // 19: vantage.v1.LsLink
	(*LsPrefix)(nil),              // 20: vantage.v1.LsPrefix
	(*LsAdjacencySid)(nil),        // 21: vantage.v1.LsAdjacencySid
	(*LsEvent)(nil),               // 22: vantage.v1.LsEvent
	(*Capabilities)(nil),          // 23: vantage.v1.Capabilities
	(*PeerEvent)(nil),             // 24: vantage.v1.PeerEvent
	(*StatsEvent)(nil),            // 25: vantage.v1.StatsEvent
	(*RawEvent)(nil),              // 26: vantage.v1.RawEvent
	(*CollectorBeat)(nil),         // 27: vantage.v1.CollectorBeat
	(*Envelope)(nil),              // 28: vantage.v1.Envelope
	nil,                           // 29: vantage.v1.LsNode.UnknownTlvsEntry
	nil,                           // 30: vantage.v1.LsLink.UnknownTlvsEntry
	nil,                           // 31: vantage.v1.LsPrefix.UnknownTlvsEntry
	nil,                           // 32: vantage.v1.LsEvent.UnknownTlvsEntry
	nil,                           // 33: vantage.v1.StatsEvent.CountersEntry
	(*timestamppb.Timestamp)(nil), // 34: google.protobuf.Timestamp
}
var file_vantage_v1_vantage_proto_depIdxs = []int32{
	1,  // 0: vantage.v1.PeerId.type:type_name -> vantage.v1.PeerType
	10, // 1: vantage.v1.PathAttributes.as_path:type_name -> vantage.v1.AsPathSegment
	11, // 2: vantage.v1.PathAttributes.aggregator:type_name -> vantage.v1.Aggregator
	13, // 3: vantage.v1.PathAttributes.extended_communities:type_name -> vantage.v1.ExtCommunity
	12, // 4: vantage.v1.PathAttributes.large_communities:type_name -> vantage.v1.LargeCommunity
	14, // 5: vantage.v1.PathAttributes.unknown:type_name -> vantage.v1.UnknownAttr
	6,  // 6: vantage.v1.RouteEvent.family:type_name -> vantage.v1.Family
	15, // 7: vantage.v1.RouteEvent.attrs:type_name -> vantage.v1.PathAttributes
	7,  // 8: vantage.v1.RouteEvent.announced:type_name -> vantage.v1.Prefix
	7,  // 9: vantage.v1.RouteEvent.withdrawn:type_name -> vantage.v1.Prefix
	8,  // 10: vantage.v1.RouteEvent.vpn_announced:type_name -> vantage.v1.VpnPrefix
	8,  // 11: vantage.v1.RouteEvent.vpn_withdrawn:type_name -> vantage.v1.VpnPrefix
	9,  // 12: vantage.v1.RouteEvent.evpn_announced:type_name -> vantage.v1.EvpnRoute
	9,  // 13: vantage.v1.RouteEvent.evpn_withdrawn:type_name -> vantage.v1.EvpnRoute
	17, // 14: vantage.v1.LsNode.local:type_name -> vantage.v1.LsNodeDescriptor
	29, // 15: vantage.v1.LsNode.unknown_tlvs:type_name -> vantage.v1.LsNode.UnknownTlvsEntry
	17, // 16: vantage.v1.LsLink.local:type_name -> vantage.v1.LsNodeDescriptor
	17, // 17: vantage.v1.LsLink.remote:type_name -> vantage.v1.LsNodeDescriptor
	21, // 18: vantage.v1.LsLink.adj_sids:type_name -> vantage.v1.LsAdjacencySid
	30, // 19: vantage.v1.LsLink.unknown_tlvs:type_name -> vantage.v1.LsLink.UnknownTlvsEntry
	17, // 20: vantage.v1.LsPrefix.local:type_name -> vantage.v1.LsNodeDescriptor
	31, // 21: vantage.v1.LsPrefix.unknown_tlvs:type_name -> vantage.v1.LsPrefix.UnknownTlvsEntry
	6,  // 22: vantage.v1.LsEvent.family:type_name -> vantage.v1.Family
	15, // 23: vantage.v1.LsEvent.attrs:type_name -> vantage.v1.PathAttributes
	18, // 24: vantage.v1.LsEvent.nodes:type_name -> vantage.v1.LsNode
	19, // 25: vantage.v1.LsEvent.links:type_name -> vantage.v1.LsLink
	32, // 26: vantage.v1.LsEvent.unknown_tlvs:type_name -> vantage.v1.LsEvent.UnknownTlvsEntry
	20, // 27: vantage.v1.LsEvent.prefixes:type_name -> vantage.v1.LsPrefix
	6,  // 28: vantage.v1.Capabilities.addpath_families:type_name -> vantage.v1.Family
	6,  // 29: vantage.v1.Capabilities.mp_families:type_name -> vantage.v1.Family
	2,  // 30: vantage.v1.PeerEvent.kind:type_name -> vantage.v1.PeerEvent.Kind
	23, // 31: vantage.v1.PeerEvent.caps:type_name -> vantage.v1.Capabilities
	33, // 32: vantage.v1.StatsEvent.counters:type_name -> vantage.v1.StatsEvent.CountersEntry
	34, // 33: vantage.v1.CollectorBeat.started_at:type_name -> google.protobuf.Timestamp
	3,  // 34: vantage.v1.Envelope.router:type_name -> vantage.v1.RouterId
	5,  // 35: vantage.v1.Envelope.peer:type_name -> vantage.v1.PeerId
	34, // 36: vantage.v1.Envelope.ts_router:type_name -> google.protobuf.Timestamp
	34, // 37: vantage.v1.Envelope.ts_collector:type_name -> google.protobuf.Timestamp
	4,  // 38: vantage.v1.Envelope.router_info:type_name -> vantage.v1.RouterInfo
	0,  // 39: vantage.v1.Envelope.parse_flags:type_name -> vantage.v1.ParseFlag
	16, // 40: vantage.v1.Envelope.route:type_name -> vantage.v1.RouteEvent
	22, // 41: vantage.v1.Envelope.ls:type_name -> vantage.v1.LsEvent
	24, // 42: vantage.v1.Envelope.peer_event:type_name -> vantage.v1.PeerEvent
	25, // 43: vantage.v1.Envelope.stats:type_name -> vantage.v1.StatsEvent
	26, // 44: vantage.v1.Envelope.raw:type_name -> vantage.v1.RawEvent
	27, // 45: vantage.v1.Envelope.beat:type_name -> vantage.v1.CollectorBeat
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_vantage_v1_vantage_proto_init() }
func file_vantage_v1_vantage_proto_init() {
	if File_vantage_v1_vantage_proto != nil {
		return
	}
	file_vantage_v1_vantage_proto_msgTypes[12].OneofWrappers = []any{}
	file_vantage_v1_vantage_proto_msgTypes[25].OneofWrappers = []any{
		(*Envelope_Route)(nil),
		(*Envelope_Ls)(nil),
		(*Envelope_PeerEvent)(nil),
		(*Envelope_Stats)(nil),
		(*Envelope_Raw)(nil),
		(*Envelope_Beat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vantage_v1_vantage_proto_rawDesc), len(file_vantage_v1_vantage_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vantage_v1_vantage_proto_goTypes,
		DependencyIndexes: file_vantage_v1_vantage_proto_depIdxs,
		EnumInfos:         file_vantage_v1_vantage_proto_enumTypes,
		MessageInfos:      file_vantage_v1_vantage_proto_msgTypes,
	}.Build()
	File_vantage_v1_vantage_proto = out.File
	file_vantage_v1_vantage_proto_goTypes = nil
	file_vantage_v1_vantage_proto_depIdxs = nil
}
